# Generated by Django 5.0.4 on 2024-07-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hero_flashhero_spiderhero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderhero',
            name='hero_ptr',
        ),
        migrations.DeleteModel(
            name='FlashHero',
        ),
        migrations.DeleteModel(
            name='SpiderHero',
        ),
        migrations.CreateModel(
            name='FlashHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero',),
        ),
        migrations.CreateModel(
            name='SpiderHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero',),
        ),
    ]
