# Generated by Django 5.0.4 on 2024-06-25 20:47
import random
from random import sample

from django.db import migrations


def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    all_barcodes = random.sample(range(100000000, 1000000000), len(all_products))

    for product, current_barcode in zip(all_products, all_barcodes):
        product.barcode = current_barcode
        product.save()


def reverse_add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()

    for product in all_products:
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_add_barcode)
    ]
